const STORAGE_KEY='grammarShooterTopicsV1', SOUND_KEY='grammarShooterSound';
const palette=['#7956ff','#ff5fa2','#35d8f5','#4cdf9a','#ff9f43'];
const presets=[
 {id:'present-simple',title:'Present Simple',description:'Действия, которые происходят регулярно',icon:'⏰',accent:'#7956ff',questions:[
  ['She ___ to school every day.','goes','go','going','После she к глаголу добавляем -s.'],['I ___ my teeth every morning.','brush','brushes','brushing','После I используем начальную форму глагола.'],['Tom ___ football on Sundays.','plays','play','playing','После he, she, it добавляем -s.'],['We ___ English at school.','study','studies','studying','После we глагол не получает окончание -s.'],['My cat ___ on the sofa.','sleeps','sleep','sleeping','My cat — это it, поэтому добавляем -s.'],['They ___ TV in the evening.','watch','watches','watching','После they используем начальную форму.'],['Ann ___ her homework after lunch.','does','do','doing','Форма do после she — does.'],['___ you like ice cream?','Do','Does','Are','В вопросе с you используем Do.'],['___ he live in London?','Does','Do','Is','В вопросе с he используем Does.'],['Ben does not ___ coffee.','drink','drinks','drinking','После does not глагол стоит в начальной форме.']]},
 {id:'there-is-are',title:'There is / There are',description:'Один предмет или несколько предметов',icon:'🪐',accent:'#ff5fa2',questions:[
  ['___ a book on the desk.','There is','There are','They are','Для одного предмета используем There is.'],['___ three apples in the bag.','There are','There is','It is','Для нескольких предметов используем There are.'],['___ a dog in the garden.','There is','There are','There am','A dog — один предмет.'],['___ two windows in my room.','There are','There is','They is','Two windows — несколько предметов.'],['___ some milk in the glass.','There is','There are','They are','Milk — неисчисляемое существительное.'],['___ many stars in the sky.','There are','There is','It are','Stars во множественном числе.'],['___ an orange on the plate.','There is','There are','They are','An orange — один предмет.'],['___ five children in the park.','There are','There is','It is','Five children — несколько человек.'],['Is ___ a computer here?','there','they','these','В вопросе сохраняется слово there.'],['Are ___ any pencils?','there','it','that','В вопросе с Are используем there.']]},
 {id:'have-has-got',title:'Have got / Has got',description:'Говорим о том, что у кого-то есть',icon:'🎒',accent:'#35d8f5',questions:[
  ['I ___ a new bike.','have got','has got','am got','После I используем have got.'],['She ___ blue eyes.','has got','have got','is got','После she используем has got.'],['We ___ a big classroom.','have got','has got','are got','После we используем have got.'],['My brother ___ a pet hamster.','has got','have got','got have','My brother — это he.'],['They ___ two dogs.','have got','has got','are have','После they используем have got.'],['Tom and Sam ___ a football.','have got','has got','is got','Два человека — это they.'],['The bird ___ small wings.','has got','have got','is have','The bird — это it.'],['___ you got a pencil?','Have','Has','Do','В вопросе с you используем Have.'],['___ Kate got a sister?','Has','Have','Does','В вопросе с Kate (she) используем Has.'],['He ___ not got a phone.','has','have','does','После he используем has not got.']]}
].map(t=>({...t,builtin:true,questions:t.questions.map(q=>({sentence:q[0],correct:q[1],wrong:[q[2],q[3]],explanation:q[4]}))}));

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let customTopics=loadTopics(), soundOn=localStorage.getItem(SOUND_KEY)!=='false', currentTopic=null, game=null, editing=null, modalAction=null, audioCtx=null;

function loadTopics(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return []}}
function saveTopics(){localStorage.setItem(STORAGE_KEY,JSON.stringify(customTopics))}
function uid(){return 'topic-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$('#app').focus();scrollTo(0,0)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function sound(type){if(!soundOn)return; audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();let f=300,d=.12; if(type==='hit'){f=520;d=.12}else if(type==='wrong'){f=150;d=.25}else if(type==='win'){f=720;d=.4}else if(type==='click'){f=260;d=.05}o.type=type==='wrong'?'sawtooth':'sine';o.frequency.setValueAtTime(f,audioCtx.currentTime);if(type==='win')o.frequency.exponentialRampToValueAtTime(1100,audioCtx.currentTime+d);g.gain.setValueAtTime(.09,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}

function topicCard(t,i){return `<article class="topic-card" style="--accent:${t.accent||palette[i%palette.length]}"><div class="topic-icon">${t.icon||'✦'}</div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.description||'Пользовательская грамматическая тема')}</p><div class="topic-meta"><span>10 заданий · 3 жизни</span><button class="play-button" data-play="${escapeHtml(t.id)}">Играть →</button></div></article>`}
function renderHome(){$('#presetTopics').innerHTML=presets.map(topicCard).join('');$('#customTopics').innerHTML=customTopics.map(topicCard).join('');$('#customSection').classList.toggle('hidden',!customTopics.length)}
function findTopic(id){return [...presets,...customTopics].find(t=>t.id===id)}

function startGame(topic){if(!topic||topic.questions.length<10){toast('В теме должно быть 10 вопросов');return}currentTopic=topic;game={questions:shuffle(topic.questions).slice(0,10),index:0,lives:3,mistakes:0,destroyed:0,done:false};showScreen('gameScreen');renderQuestion()}
function renderQuestion(){const q=game.questions[game.index];game.destroyed=0;game.done=false;$('#gameTopic').textContent=currentTopic.title;$('#gameProgress').textContent=`${game.index+1} / 10`;$('#progressBar').style.width=`${(game.index+1)*10}%`;renderLives();$('#sentence').innerHTML=escapeHtml(q.sentence).replace('___','<span class="blank">___</span>');$('#feedback').innerHTML='';const answers=shuffle([{text:q.correct,correct:true},...q.wrong.map(text=>({text,correct:false}))]);$('#targets').innerHTML=answers.map((a,i)=>`<button class="target" data-correct="${a.correct}" data-key="${i+1}">${escapeHtml(a.text)}</button>`).join('')}
function renderLives(){$('#lives').innerHTML=Array.from({length:3},(_,i)=>i<game.lives?'❤️':'🖤').join('')}
function shoot(target){if(game.done||target.classList.contains('destroyed'))return;sound('click');if(target.dataset.correct==='true'){game.lives--;game.mistakes++;target.classList.add('protected');setTimeout(()=>target.classList.remove('protected'),500);renderLives();$('#feedback').innerHTML='<div class="feedback-card">🛡️ <b>Этот ответ подходит!</b> Его нужно сохранить.</div>';sound('wrong');if(game.lives<=0)setTimeout(()=>finishGame(false),650)}else{target.classList.add('destroyed');game.destroyed++;sound('hit');$('#feedback').innerHTML='<div class="feedback-card">🎯 Отличное попадание! Это неверный ответ.</div>';if(game.destroyed===2)setTimeout(completeQuestion,500)}}
function completeQuestion(){game.done=true;const q=game.questions[game.index];$('#sentence').innerHTML=escapeHtml(q.sentence).replace('___',`<span class="blank">${escapeHtml(q.correct)}</span>`);$$('.target').forEach(b=>b.disabled=true);$('#feedback').innerHTML=`<div class="feedback-card">✨ <b>Верно!</b> ${escapeHtml(q.explanation||'Правильный ответ сохранён.')} <button class="play-button next-button" id="nextQuestion">Дальше →</button></div>`;sound('win')}
function nextQuestion(){if(game.index===9)finishGame(true);else{game.index++;renderQuestion()}}
function finishGame(won){showScreen('resultScreen');$('#resultIcon').textContent=won?'🏆':'🌟';$('#resultTitle').textContent=won?'Миссия выполнена!':'Почти получилось!';$('#resultText').textContent=won?'Ты спас все правильные ответы. Отличная работа!':'Ошибки помогают учиться. Давай попробуем ещё раз!';$('#statQuestions').textContent=won?10:game.index;$('#statLives').textContent=game.lives;$('#statMistakes').textContent=game.mistakes;sound(won?'win':'wrong')}

function openEditor(){renderEditorList();$('#editorListView').classList.remove('hidden');$('#editorFormView').classList.add('hidden');showScreen('editorScreen')}
function renderEditorList(){const all=[...presets,...customTopics];$('#editorTopicList').innerHTML=all.map(t=>`<article class="editor-list-card"><div><h3>${t.builtin?'🔒 ':'✦ '}${escapeHtml(t.title)}</h3><p>${t.builtin?'Готовая тема · можно создать копию':'Моя тема'} · ${t.questions.length} вопросов</p></div><div class="mini-actions"><button title="Играть" data-editor-play="${t.id}">▶</button><button title="${t.builtin?'Создать копию':'Редактировать'}" data-edit="${t.id}">${t.builtin?'⧉':'✎'}</button>${t.builtin?'':`<button title="Экспортировать" data-export="${t.id}">⇩</button><button title="Удалить" data-delete="${t.id}">🗑</button>`}</div></article>`).join('')}
function blankQuestion(){return{sentence:'',correct:'',wrong:['',''],explanation:''}}
function editTopic(t){editing=t?JSON.parse(JSON.stringify(t)):{id:uid(),title:'',description:'',icon:'✦',accent:palette[customTopics.length%palette.length],questions:[blankQuestion()]};if(editing.builtin){editing.id=uid();editing.title+=' — копия';delete editing.builtin}$('#topicTitle').value=editing.title;$('#topicDescription').value=editing.description||'';$('#editorListView').classList.add('hidden');$('#editorFormView').classList.remove('hidden');renderQuestions()}
function renderQuestions(){const n=editing.questions.length;$('#questionCounter').textContent=`${n} из 10 добавлено`;$('#addQuestion').disabled=n>=10;$('#questionList').innerHTML=editing.questions.map((q,i)=>`<article class="question-card"><div class="question-number">${i+1}</div><div><div class="question-grid"><label>Предложение с ___<input data-field="sentence" data-i="${i}" value="${escapeHtml(q.sentence)}" placeholder="She ___ to school."></label><label>✓ Правильный<input data-field="correct" data-i="${i}" value="${escapeHtml(q.correct)}"></label><label>✕ Неверный 1<input data-field="wrong0" data-i="${i}" value="${escapeHtml(q.wrong[0])}"></label><label>✕ Неверный 2<input data-field="wrong1" data-i="${i}" value="${escapeHtml(q.wrong[1])}"></label></div><div class="explanation-row"><label>Объяснение (необязательно)<input data-field="explanation" data-i="${i}" value="${escapeHtml(q.explanation||'')}" placeholder="Коротко объясни правило"></label><div class="question-actions"><button data-move-up="${i}" title="Выше">↑</button><button data-move-down="${i}" title="Ниже">↓</button><button data-duplicate="${i}" title="Дублировать">⧉</button><button data-remove="${i}" title="Удалить">🗑</button></div></div></div></article>`).join('');$('#saveStatus').textContent='Все изменения сохранены'}
function syncEditor(){editing.title=$('#topicTitle').value;editing.description=$('#topicDescription').value;$('#saveStatus').textContent='Есть несохранённые изменения'}
function validateTopic(t){if(!t.title.trim())return 'Введите название темы.';if(t.questions.length!==10)return 'Добавьте ровно 10 вопросов.';for(let i=0;i<t.questions.length;i++){const q=t.questions[i],matches=(q.sentence.match(/___/g)||[]).length;if(matches!==1)return `В вопросе ${i+1} должен быть ровно один пропуск ___.`;const a=[q.correct,...q.wrong].map(x=>x.trim().toLowerCase());if(a.some(x=>!x))return `Заполните все ответы в вопросе ${i+1}.`;if(new Set(a).size!==3)return `Ответы в вопросе ${i+1} не должны повторяться.`}return ''}
function persistEditing(play=false){syncEditor();const err=validateTopic(editing);$('#formError').textContent=err;if(err)return;const idx=customTopics.findIndex(t=>t.id===editing.id);if(idx>=0)customTopics[idx]=editing;else customTopics.push(editing);saveTopics();$('#saveStatus').textContent='Все изменения сохранены';toast('Тема сохранена');renderHome();if(play)startGame(editing);else{renderEditorList();$('#editorFormView').classList.add('hidden');$('#editorListView').classList.remove('hidden')}}
function exportTopic(t){const blob=new Blob([JSON.stringify({...t,builtin:undefined},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=t.title.replace(/[^a-zа-я0-9]+/gi,'-').toLowerCase()+'.json';a.click();URL.revokeObjectURL(a.href)}
function importTopic(file){const reader=new FileReader();reader.onload=()=>{try{const t=JSON.parse(reader.result);t.id=uid();delete t.builtin;const err=validateTopic(t);if(err)throw new Error(err);customTopics.push(t);saveTopics();renderHome();renderEditorList();toast('Тема импортирована')}catch(e){toast('Не удалось импортировать: '+e.message)}};reader.readAsText(file)}
function confirmModal(title,text,action){$('#modalTitle').textContent=title;$('#modalText').textContent=text;modalAction=action;$('#modal').classList.remove('hidden')}

document.addEventListener('click',e=>{const b=e.target.closest('button,[data-action]');if(!b)return;const action=b.dataset.action;if(action==='home'){renderHome();showScreen('homeScreen')}if(action==='editor')openEditor();if(action==='replay')startGame(currentTopic);if(action==='confirm-home')confirmModal('Покинуть миссию?','Текущий прогресс не сохранится.',()=>{renderHome();showScreen('homeScreen')});if(b.dataset.play)startGame(findTopic(b.dataset.play));if(b.classList.contains('target'))shoot(b);if(b.id==='nextQuestion')nextQuestion();if(b.id==='newTopicButton')editTopic();if(b.id==='backToTopics'){renderEditorList();$('#editorFormView').classList.add('hidden');$('#editorListView').classList.remove('hidden')}if(b.dataset.editorPlay)startGame(findTopic(b.dataset.editorPlay));if(b.dataset.edit)editTopic(findTopic(b.dataset.edit));if(b.dataset.export)exportTopic(findTopic(b.dataset.export));if(b.dataset.delete)confirmModal('Удалить тему?','Восстановить её будет невозможно.',()=>{customTopics=customTopics.filter(t=>t.id!==b.dataset.delete);saveTopics();renderHome();renderEditorList();toast('Тема удалена')});if(b.id==='addQuestion'&&editing.questions.length<10){editing.questions.push(blankQuestion());renderQuestions()}if(b.dataset.remove!==undefined)confirmModal('Удалить вопрос?','Остальные вопросы сохранятся.',()=>{editing.questions.splice(+b.dataset.remove,1);renderQuestions()});if(b.dataset.duplicate!==undefined&&editing.questions.length<10){editing.questions.splice(+b.dataset.duplicate+1,0,JSON.parse(JSON.stringify(editing.questions[+b.dataset.duplicate])));renderQuestions()}if(b.dataset.moveUp!==undefined&&+b.dataset.moveUp>0){let i=+b.dataset.moveUp;[editing.questions[i-1],editing.questions[i]]=[editing.questions[i],editing.questions[i-1]];renderQuestions()}if(b.dataset.moveDown!==undefined&&+b.dataset.moveDown<editing.questions.length-1){let i=+b.dataset.moveDown;[editing.questions[i+1],editing.questions[i]]=[editing.questions[i],editing.questions[i+1]];renderQuestions()}if(b.id==='saveTopic')persistEditing();if(b.id==='saveAndPlay')persistEditing(true)});
document.addEventListener('input',e=>{if(!editing)return;if(e.target.id==='topicTitle'||e.target.id==='topicDescription')syncEditor();if(e.target.dataset.field){const q=editing.questions[+e.target.dataset.i],f=e.target.dataset.field;if(f==='wrong0')q.wrong[0]=e.target.value;else if(f==='wrong1')q.wrong[1]=e.target.value;else q[f]=e.target.value;$('#saveStatus').textContent='Есть несохранённые изменения'}});
document.addEventListener('keydown',e=>{if($('#gameScreen').classList.contains('active')){if(['1','2','3'].includes(e.key))$$('.target')[+e.key-1]?.click();if(e.key==='Enter'&&game?.done)nextQuestion();if(e.key==='Escape')confirmModal('Покинуть миссию?','Текущий прогресс не сохранится.',()=>{renderHome();showScreen('homeScreen')})}});
$('#soundButton').onclick=()=>{soundOn=!soundOn;localStorage.setItem(SOUND_KEY,soundOn);$('#soundButton').textContent=soundOn?'🔊':'🔇';$('#soundButton').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук');if(soundOn)sound('click')};
$('#importInput').onchange=e=>{if(e.target.files[0])importTopic(e.target.files[0]);e.target.value=''};
$('#modalCancel').onclick=()=>$('#modal').classList.add('hidden');$('#modalConfirm').onclick=()=>{modalAction?.();modalAction=null;$('#modal').classList.add('hidden')};
$('#soundButton').textContent=soundOn?'🔊':'🔇';renderHome();
